import { defineConfig } from 'orval';

export default defineConfig({
  api: {
    input: {
      target: 'http://localhost:3001/api-json',
      filters: {
        tags: ['Auth', 'Profiles', 'Coops'],
      },
    },
    output: {
      mode: 'tags-split',
      target: 'src/shared/open-api/api.ts',
      schemas: 'src/shared/open-api/models',
      client: 'fetch',
      clean: true,
      override: {
        header: (info) => [
          `eslint-disable`,
          `Generated by orval v${info.version} 🍺`,
          `Do not edit manually.`,
          ...(info.title ? [info.title] : []),
        ],
        mutator: {
          path: 'src/shared/interceptors/open-api.mutator.ts',
          name: 'openApiMutator',
        },
      },
    },
    hooks: {
      afterAllFilesWrite: 'eslint --fix',
    },
  },
});
