 
/**
 * Generated by orval v1.0 🍺
 * Do not edit manually.
 * MCP Coop Backend API
 */
import type {
  Skill,
  SkillsControllerFindAll200AllOf,
  SkillsControllerFindAllParams
} from '.././models';

import { openApiMutator } from '../../interceptors/open-api.mutator';

/**
 * @summary List skills (optionally filtered by category)
 */
export type skillsControllerFindAllResponse200 = {
  data: SkillsControllerFindAll200AllOf
  status: 200
}
    
export type skillsControllerFindAllResponseSuccess = (skillsControllerFindAllResponse200) & {
  headers: Headers;
};
;

export type skillsControllerFindAllResponse = (skillsControllerFindAllResponseSuccess)

export const getSkillsControllerFindAllUrl = (params?: SkillsControllerFindAllParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/skills?${stringifiedParams}` : `/api/skills`
}

export const skillsControllerFindAll = async (params?: SkillsControllerFindAllParams, options?: RequestInit): Promise<skillsControllerFindAllResponse> => {
  
  return openApiMutator<skillsControllerFindAllResponse>(getSkillsControllerFindAllUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Get a skill by ID
 */
export type skillsControllerFindOneResponse200 = {
  data: Skill
  status: 200
}
    
export type skillsControllerFindOneResponseSuccess = (skillsControllerFindOneResponse200) & {
  headers: Headers;
};
;

export type skillsControllerFindOneResponse = (skillsControllerFindOneResponseSuccess)

export const getSkillsControllerFindOneUrl = (id: string,) => {


  

  return `/api/skills/${id}`
}

export const skillsControllerFindOne = async (id: string, options?: RequestInit): Promise<skillsControllerFindOneResponse> => {
  
  return openApiMutator<skillsControllerFindOneResponse>(getSkillsControllerFindOneUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


