 
/**
 * Generated by orval v1.0 🍺
 * Do not edit manually.
 * Micro App API
 */

export interface AddAccountSkillDto {
  /**
   * Proficiency level (1 = beginner, 5 = expert)
   * @minimum 1
   * @maximum 5
   */
  level?: number;
}
