 
/**
 * Generated by orval v1.0 🍺
 * Do not edit manually.
 * Micro App API
 */
import type { BlockchainAccountResponseDtoAccountType } from './blockchainAccountResponseDtoAccountType';

export interface BlockchainAccountResponseDto {
  /** Wallet address (public key) */
  address: string;
  /** Type of the external account (e.g., WALLET) */
  accountType: BlockchainAccountResponseDtoAccountType;
  /** Whether the account is frozen/banned on-chain */
  frozen: boolean;
  /** Account balance representation or mapped tokens */
  balance: string;
  /** When the account was registered on-chain originally */
  onChainCreatedAt: string;
  /** One-time nonce for SIWE authentication */
  nonce: string;
  /** Timestamp when this record was created in the database */
  createdAt: string;
  /** Timestamp of the last database internal update */
  updatedAt: string;
}
