 
/**
 * Generated by orval v1.0 🍺
 * Do not edit manually.
 * Micro App API
 */

/**
 * Type of the external account (e.g., WALLET)
 */
export type BlockchainAccountResponseDtoAccountType = typeof BlockchainAccountResponseDtoAccountType[keyof typeof BlockchainAccountResponseDtoAccountType];


 
export const BlockchainAccountResponseDtoAccountType = {
  COOP: 'COOP',
  WALLET: 'WALLET',
} as const;
