 
/**
 * Generated by orval v1.0 🍺
 * Do not edit manually.
 * MCP Coop Backend API
 */

export interface ContactDto {
  /**
   * Platform name (e.g. TELEGRAM, EMAIL)
   * @maxLength 100
   */
  platform: string;
  /**
   * Contact handle or address
   * @maxLength 200
   */
  value: string;
}
