 
/**
 * Generated by orval v1.0 🍺
 * Do not edit manually.
 * MCP Coop Backend API
 */
import type { CoopResponseDtoStatus } from './coopResponseDtoStatus';
import type { CoopResponseDtoContacts } from './coopResponseDtoContacts';
import type { CoopResponseDtoWallets } from './coopResponseDtoWallets';
import type { CoopMemberResponseDto } from './coopMemberResponseDto';

export interface CoopResponseDto {
  /** Internal UUID of the Cooperative */
  id: string;
  /** On-chain ID of the Cooperative */
  onChainId: string;
  /** Current status of the Cooperative */
  status: CoopResponseDtoStatus;
  /** Name of the Cooperative */
  name: string;
  /**
   * Description of the Cooperative
   * @nullable
   */
  description?: string | null;
  /** Industry categories associated with this cooperative */
  categories: string[];
  /** Array of contacts associated with the cooperative */
  contacts?: CoopResponseDtoContacts;
  /** Array of blockchain wallets associated with the cooperative */
  wallets: CoopResponseDtoWallets;
  /**
   * Website URL
   * @nullable
   */
  website?: string | null;
  /**
   * Logo image URL
   * @nullable
   */
  logoUrl?: string | null;
  /** Calculated rating (0-5) */
  rating: number;
  /**
   * Creation date on the blockchain
   * @nullable
   */
  onChainCreatedAt?: string | null;
  /** System creation date */
  createdAt: string;
  /** System update date */
  updatedAt: string;
  /** Enriched members list (derived from on-chain data and Profile) */
  members: CoopMemberResponseDto[];
}
