 
/**
 * Generated by orval v1.0 🍺
 * Do not edit manually.
 * Micro App API
 */

/**
 * Current status of the Cooperative
 */
export type CoopFullResponseDtoStatus = typeof CoopFullResponseDtoStatus[keyof typeof CoopFullResponseDtoStatus];


 
export const CoopFullResponseDtoStatus = {
  ACTIVE: 'ACTIVE',
  FROZEN: 'FROZEN',
  CLOSED: 'CLOSED',
} as const;
