 
/**
 * Generated by orval v1.0 🍺
 * Do not edit manually.
 * MCP Coop Backend API
 */

/**
 * Array of contacts associated with the cooperative
 */
export type CoopFullResponseDtoContacts = { [key: string]: unknown };
