 
/**
 * Generated by orval v1.0 🍺
 * Do not edit manually.
 * MCP Coop Backend API
 */

/**
 * Array of blockchain wallets associated with the cooperative
 */
export type CoopFullResponseDtoWallets = { [key: string]: unknown };
