 
/**
 * Generated by orval v1.0 🍺
 * Do not edit manually.
 * MCP Coop Backend API
 */
import type { CoopFullResponseDtoStatus } from './coopFullResponseDtoStatus';
import type { CoopFullResponseDtoContacts } from './coopFullResponseDtoContacts';
import type { CoopFullResponseDtoWallets } from './coopFullResponseDtoWallets';
import type { CoopMemberResponseDto } from './coopMemberResponseDto';
import type { CoopFullResponseDtoDescription } from './coopFullResponseDtoDescription';
import type { CoopPresentationSlideDto } from './coopPresentationSlideDto';

export interface CoopFullResponseDto {
  /** Internal UUID of the Cooperative */
  id: string;
  /** On-chain ID of the Cooperative */
  onChainId: string;
  /** Current status of the Cooperative */
  status: CoopFullResponseDtoStatus;
  /** Name of the Cooperative */
  name: string;
  /** Industry categories associated with this cooperative */
  categories: string[];
  /** Array of contacts associated with the cooperative */
  contacts?: CoopFullResponseDtoContacts;
  /** Array of blockchain wallets associated with the cooperative */
  wallets: CoopFullResponseDtoWallets;
  /**
   * Website URL
   * @nullable
   */
  website?: string | null;
  /**
   * Logo image URL
   * @nullable
   */
  logoUrl?: string | null;
  /** Calculated rating (0-5) */
  rating: number;
  /**
   * Creation date on the blockchain
   * @nullable
   */
  onChainCreatedAt?: string | null;
  /** System creation date */
  createdAt: string;
  /** System update date */
  updatedAt: string;
  /** Enriched members list (derived from on-chain data and Profile) */
  members: CoopMemberResponseDto[];
  /** @nullable */
  shortDescription?: string | null;
  /** @nullable */
  description?: CoopFullResponseDtoDescription;
  /** @nullable */
  mission?: string | null;
  /** @nullable */
  vision?: string | null;
  presentationSlides: CoopPresentationSlideDto[];
}
