 
/**
 * Generated by orval v1.0 🍺
 * Do not edit manually.
 * MCP Coop Backend API
 */

export interface CoopPresentationSlideDto {
  id: string;
  order: number;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  description?: string | null;
  mediaUrl: string;
}
