 
/**
 * Generated by orval v1.0 🍺
 * Do not edit manually.
 * Micro App API
 */

/**
 * Current status of the Cooperative
 */
export type CoopResponseDtoStatus = typeof CoopResponseDtoStatus[keyof typeof CoopResponseDtoStatus];


 
export const CoopResponseDtoStatus = {
  ACTIVE: 'ACTIVE',
  FROZEN: 'FROZEN',
  CLOSED: 'CLOSED',
} as const;
