 
/**
 * Generated by orval v1.0 🍺
 * Do not edit manually.
 * MCP Coop Backend API
 */
import type { CoopResponseDto } from './coopResponseDto';
import type { PaginationMetaDto } from './paginationMetaDto';

export type CoopsControllerFindAll200AllOf = {
  data?: CoopResponseDto[];
  meta?: PaginationMetaDto;
};
