 
/**
 * Generated by orval v1.0 🍺
 * Do not edit manually.
 * Micro App API
 */

export interface CoopMemberResponseDto {
  /** Member ID (UUID) within the Coop */
  id: string;
  /** On-chain wallet address of the member */
  walletAddress: string;
  /** Display name resolved via Profile fallback (fullName -> username -> email -> walletAddress) */
  name: string;
  /**
   * Role derived from Profile
   * @nullable
   */
  role?: string | null;
  /**
   * Avatar URL derived from ProfileSettings
   * @nullable
   */
  avatarUrl?: string | null;
  /** Indicates if the member is the proposer/creator on-chain */
  isProposer: boolean;
}
