 
/**
 * Generated by orval v1.0 🍺
 * Do not edit manually.
 * Micro App API
 */

/**
 * Dictionary of contacts (telegram, email, etc.)
 * @nullable
 */
export type CoopResponseDtoContacts = { [key: string]: unknown } | null;
