 
/**
 * Generated by orval v1.0 🍺
 * Do not edit manually.
 * Micro App API
 */

export interface CoopMemberResponseDto {
  /** Member ID (UUID) within the Coop */
  id: string;
  /** On-chain wallet address of the member */
  onChainId: string;
  /** Display name resolved via Profile fallback (fullName -> username -> email -> on-chain id) */
  name: string;
  /**
   * Avatar URL derived from ProfileSettings
   * @nullable
   */
  avatarUrl?: string | null;
  /** Indicates if the member is the proposer/creator on-chain */
  isProposer: boolean;
  /**
   * Platform profile UUID when this wallet is linked to a user; null otherwise
   * @nullable
   */
  profileId?: string | null;
  /**
   * Primary competence category derived from profile skills
   * @nullable
   */
  competence?: string | null;
}
