 
/**
 * Generated by orval v1.0 🍺
 * Do not edit manually.
 * Micro App API
 */

/**
 * Dictionary of blockchain wallets by network
 */
export type CoopFullResponseDtoWallets = { [key: string]: unknown };
