 
/**
 * Generated by orval v1.0 🍺
 * Do not edit manually.
 * Micro App API
 */

/**
 * Task priority
 */
export type CreateTaskDtoPriority = typeof CreateTaskDtoPriority[keyof typeof CreateTaskDtoPriority];


 
export const CreateTaskDtoPriority = {
  low: 'low',
  medium: 'medium',
  high: 'high',
  critical: 'critical',
} as const;
