 
/**
 * Generated by orval v1.0 🍺
 * Do not edit manually.
 * Micro App API
 */

export interface CreateTaskCriterionDto {
  /**
   * Criterion text
   * @maxLength 5000
   */
  text: string;
  /**
   * Display order
   * @minimum 0
   */
  sortOrder?: number;
}
