 
/**
 * Generated by orval v1.0 🍺
 * Do not edit manually.
 * Micro App API
 */

/**
 * Workspace type
 */
export type CreateWorkspaceDtoType = typeof CreateWorkspaceDtoType[keyof typeof CreateWorkspaceDtoType];


 
export const CreateWorkspaceDtoType = {
  private: 'private',
  group: 'group',
  channel: 'channel',
} as const;
