 
/**
 * Generated by orval v1.0 🍺
 * Do not edit manually.
 * Micro App API
 */
import type { CreateWorkspaceMemberDtoRole } from './createWorkspaceMemberDtoRole';

export interface CreateWorkspaceMemberDto {
  /** Workspace ID */
  workspaceId: string;
  /** User profile ID */
  userId: string;
  /** Member role */
  role?: CreateWorkspaceMemberDtoRole;
}
