 
/**
 * Generated by orval v1.0 🍺
 * Do not edit manually.
 * Micro App API
 */
import type { CreateTaskDtoPriority } from './createTaskDtoPriority';
import type { CreateTaskDtoStatus } from './createTaskDtoStatus';

export interface CreateTaskDto {
  /** Workspace ID */
  workspaceId: string;
  /** Assignee ID (defaults to creator if omitted) */
  assigneeId?: string;
  /**
   * Task title
   * @maxLength 255
   */
  title: string;
  /**
   * Task description
   * @maxLength 5000
   */
  description: string;
  /** Task priority */
  priority?: CreateTaskDtoPriority;
  /** Task status */
  status?: CreateTaskDtoStatus;
  /**
   * Additional info (plain text)
   * @maxLength 5000
   */
  info?: string;
}
