 
/**
 * Generated by orval v1.0 🍺
 * Do not edit manually.
 * Micro App API
 */

/**
 * Pricing tier
 */
export type CreateWorkspaceDtoTier = typeof CreateWorkspaceDtoTier[keyof typeof CreateWorkspaceDtoTier];


 
export const CreateWorkspaceDtoTier = {
  free: 'free',
  pro: 'pro',
} as const;
