 
/**
 * Generated by orval v1.0 🍺
 * Do not edit manually.
 * Micro App API
 */

export interface CreateSkillDto {
  /** Unique skill name */
  name: string;
  /** Grouping category */
  category?: string;
  /** Short description of the skill */
  description?: string;
}
