 
/**
 * Generated by orval v1.0 🍺
 * Do not edit manually.
 * MCP Coop Backend API
 */

export interface CreateCoopDto {
  /**
   * Name of the Cooperative
   * @maxLength 100
   */
  name: string;
  /**
   * Description of the Cooperative
   * @maxLength 2000
   */
  description?: string;
  /** Industry categories associated with this cooperative */
  categories?: string[];
}
