 
/**
 * Generated by orval v1.0 🍺
 * Do not edit manually.
 * MCP Coop Backend API
 */

export interface CreateCoopDto {
  /**
   * Name of the Cooperative
   * @maxLength 100
   */
  name: string;
  /**
   * Description of the Cooperative
   * @maxLength 2000
   */
  description?: string;
  /** Industry categories associated with this cooperative */
  categories?: string[];
  /**
   * Website URL
   * @maxLength 500
   */
  website?: string;
  /**
   * Logo image URL
   * @maxLength 500
   */
  logoUrl?: string;
  /**
   * Mission of the Cooperative
   * @maxLength 500
   */
  mission?: string;
  /**
   * Vision of the Cooperative
   * @maxLength 500
   */
  vision?: string;
}
