 
/**
 * Generated by orval v1.0 🍺
 * Do not edit manually.
 * Micro App API
 */

/**
 * Task status
 */
export type CreateTaskDtoStatus = typeof CreateTaskDtoStatus[keyof typeof CreateTaskDtoStatus];


 
export const CreateTaskDtoStatus = {
  backlog: 'backlog',
  ready_to_dev: 'ready_to_dev',
  in_dev: 'in_dev',
  blocker: 'blocker',
  in_testing: 'in_testing',
  in_review: 'in_review',
  done: 'done',
} as const;
