 
/**
 * Generated by orval v1.0 🍺
 * Do not edit manually.
 * Micro App API
 */

/**
 * Member role
 */
export type CreateWorkspaceMemberDtoRole = typeof CreateWorkspaceMemberDtoRole[keyof typeof CreateWorkspaceMemberDtoRole];


 
export const CreateWorkspaceMemberDtoRole = {
  admin: 'admin',
  member: 'member',
} as const;
