 
/**
 * Generated by orval v1.0 🍺
 * Do not edit manually.
 * Micro App API
 */
import type { CreateWorkspaceDtoType } from './createWorkspaceDtoType';
import type { CreateWorkspaceDtoTier } from './createWorkspaceDtoTier';
import type { WorkspaceSettingsDto } from './workspaceSettingsDto';

export interface CreateWorkspaceDto {
  /**
   * External ID (e.g. Telegram chat ID)
   * @maxLength 255
   */
  externalId?: string;
  /**
   * Workspace name
   * @maxLength 255
   */
  name?: string;
  /** Workspace type */
  type?: CreateWorkspaceDtoType;
  /** Pricing tier */
  tier?: CreateWorkspaceDtoTier;
  settings: WorkspaceSettingsDto;
}
