 
/**
 * Generated by orval v1.0 🍺
 * Do not edit manually.
 * MCP Coop Backend API
 */
import type { BlockchainAccountResponseDto } from './blockchainAccountResponseDto';
import type { PaginationMetaDto } from './paginationMetaDto';

export interface PaginatedBlockchainAccountsResponseDto {
  data: BlockchainAccountResponseDto[];
  meta: PaginationMetaDto;
}
