 
/**
 * Generated by orval v1.0 🍺
 * Do not edit manually.
 * Micro App API
 */

export interface ProfileSkillDto {
  id: string;
  name: string;
  category: string;
  /** @nullable */
  iconUrl?: string | null;
}
