 
/**
 * Generated by orval v1.0 🍺
 * Do not edit manually.
 * Micro App API
 */

export interface ProfileSettingsDto {
  avatarUrl?: string;
  lastActiveWorkspaceId?: string;
  walletAddress?: string;
  githubUrl?: string;
  linkedinUrl?: string;
}
