 
/**
 * Generated by orval v1.0 🍺
 * Do not edit manually.
 * Micro App API
 */
import type { ProfileSkillDto } from './profileSkillDto';
import type { ProfileFullResponseDtoContacts } from './profileFullResponseDtoContacts';
import type { ProfileFullResponseDtoWallets } from './profileFullResponseDtoWallets';
import type { ProfileFullResponseDtoDescription } from './profileFullResponseDtoDescription';
import type { ProfileExperienceDto } from './profileExperienceDto';

export interface ProfileFullResponseDto {
  id: string;
  /** @nullable */
  fullName?: string | null;
  /** @nullable */
  username?: string | null;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  headline?: string | null;
  /** @nullable */
  avatarUrl?: string | null;
  rating: number;
  skills: ProfileSkillDto[];
  contacts: ProfileFullResponseDtoContacts;
  wallets: ProfileFullResponseDtoWallets;
  /**
   * The primary on-chain wallet address used to identify the profile as an AuthIdentity
   * @nullable
   */
  blockchainAccount?: string | null;
  /** @nullable */
  shortDescription?: string | null;
  /** @nullable */
  description?: ProfileFullResponseDtoDescription;
  /** @nullable */
  location?: string | null;
  /** @nullable */
  timezone?: string | null;
  /** @nullable */
  availabilityStatus?: string | null;
  languages: string[];
  experiences: ProfileExperienceDto[];
}
