 
/**
 * Generated by orval v1.0 🍺
 * Do not edit manually.
 * Micro App API
 */
import type { ProfileSkillDto } from './profileSkillDto';
import type { ProfileResponseDtoContacts } from './profileResponseDtoContacts';
import type { ProfileResponseDtoWallets } from './profileResponseDtoWallets';

export interface ProfileResponseDto {
  id: string;
  /** @nullable */
  fullName?: string | null;
  /** @nullable */
  username?: string | null;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  avatarUrl?: string | null;
  rating: number;
  skills: ProfileSkillDto[];
  contacts: ProfileResponseDtoContacts;
  wallets: ProfileResponseDtoWallets;
  /**
   * The primary on-chain wallet address used to identify the profile as an AuthIdentity
   * @nullable
   */
  blockchainAccount?: string | null;
}
