 
/**
 * Generated by orval v1.0 🍺
 * Do not edit manually.
 * Micro App API
 */

export interface ProfileExperienceDto {
  id: string;
  companyName: string;
  projectRole: string;
  startDate: string;
  /** @nullable */
  endDate?: string | null;
  /** @nullable */
  description?: string | null;
}
