 
/**
 * Generated by orval v1.0 🍺
 * Do not edit manually.
 * MCP Coop Backend API
 */
import type { ProfileResponseDto } from './profileResponseDto';
import type { PaginationMetaDto } from './paginationMetaDto';

export type ProfilesControllerFindAll200AllOf = {
  data?: ProfileResponseDto[];
  meta?: PaginationMetaDto;
};
