 
/**
 * Generated by orval v1.0 🍺
 * Do not edit manually.
 * MCP Coop Backend API
 */

export interface PublishCoopDto {
  /**
   * On-chain ID of the Cooperative
   * @maxLength 100
   */
  realOnChainId: string;
}
