 
/**
 * Generated by orval v1.0 🍺
 * Do not edit manually.
 * Micro App API
 */

export interface RegisterBlockchainAccountDto {
  /** Wallet address (public key) */
  address: string;
  /** Optional self-description */
  description?: string;
}
