 
/**
 * Generated by orval v1.0 🍺
 * Do not edit manually.
 * Micro App API
 */

export interface RegisterDto {
  /** Email address */
  email: string;
  /** Password */
  password: string;
  username?: string;
  fullName?: string;
}
