 
/**
 * Generated by orval v1.0 🍺
 * Do not edit manually.
 * MCP Coop Backend API
 */

export interface SkillDto {
  /**
   * Skill name
   * @maxLength 100
   */
  name: string;
  /**
   * Skill level (1-5)
   * @minimum 1
   * @maximum 5
   */
  level: number;
}
