 
/**
 * Generated by orval v1.0 🍺
 * Do not edit manually.
 * MCP Coop Backend API
 */
import type { Skill } from './skill';
import type { PaginationMetaDto } from './paginationMetaDto';

export type SkillsControllerFindAll200AllOf = {
  data?: Skill[];
  meta?: PaginationMetaDto;
};
