 
/**
 * Generated by orval v1.0 🍺
 * Do not edit manually.
 * MCP Coop Backend API
 */
import type { WalletDto } from './walletDto';

export interface SyncWalletsDto {
  /** Array of blockchain wallets associated with the user profile */
  wallets: WalletDto[];
}
