 
/**
 * Generated by orval v1.0 🍺
 * Do not edit manually.
 * MCP Coop Backend API
 */
import type { SkillDto } from './skillDto';

export interface SyncSkillsDto {
  /** Array of skills associated with the user profile */
  skills: SkillDto[];
}
