 
/**
 * Generated by orval v1.0 🍺
 * Do not edit manually.
 * MCP Coop Backend API
 */
import type { CoopContactDto } from './coopContactDto';

export interface SyncCoopContactsDto {
  /** Array of contacts associated with the cooperative */
  contacts: CoopContactDto[];
}
