 
/**
 * Generated by orval v1.0 🍺
 * Do not edit manually.
 * MCP Coop Backend API
 */
import type { ContactDto } from './contactDto';

export interface SyncContactsDto {
  /** Array of contacts associated with the user profile */
  contacts: ContactDto[];
}
