 
/**
 * Generated by orval v1.0 🍺
 * Do not edit manually.
 * MCP Coop Backend API
 */
import type { CoopWalletDto } from './coopWalletDto';

export interface SyncCoopWalletsDto {
  /** Array of blockchain wallets associated with the cooperative */
  wallets: CoopWalletDto[];
}
