 
/**
 * Generated by orval v1.0 🍺
 * Do not edit manually.
 * Micro App API
 */
import type { TaskCommentAuthor } from './taskCommentAuthor';

export interface TaskComment {
  id: string;
  taskId: string;
  authorId: string;
  content: string;
  isEdited: boolean;
  isDeleted: boolean;
  author?: TaskCommentAuthor;
  createdAt: string;
  updatedAt: string;
}
