 
/**
 * Generated by orval v1.0 🍺
 * Do not edit manually.
 * Micro App API
 */

export type TaskResponseDtoPriority = typeof TaskResponseDtoPriority[keyof typeof TaskResponseDtoPriority];


 
export const TaskResponseDtoPriority = {
  low: 'low',
  medium: 'medium',
  high: 'high',
  critical: 'critical',
} as const;
