 
/**
 * Generated by orval v1.0 🍺
 * Do not edit manually.
 * Micro App API
 */
import type { TaskProfileSettingsDto } from './taskProfileSettingsDto';

/**
 * @nullable
 */
export type TaskProfileDtoSettings = TaskProfileSettingsDto | null;
