 
/**
 * Generated by orval v1.0 🍺
 * Do not edit manually.
 * Micro App API
 */
import type { TaskProfileDtoSettings } from './taskProfileDtoSettings';

export interface TaskProfileDto {
  id: string;
  /** @nullable */
  username?: string | null;
  /** @nullable */
  fullName?: string | null;
  /** @nullable */
  settings?: TaskProfileDtoSettings;
}
