 
/**
 * Generated by orval v1.0 🍺
 * Do not edit manually.
 * Micro App API
 */
import type { TaskResponseDtoStatus } from './taskResponseDtoStatus';
import type { TaskResponseDtoPriority } from './taskResponseDtoPriority';
import type { TaskProfileDto } from './taskProfileDto';

export interface TaskResponseDto {
  /** Task UUID */
  id: string;
  /** Workspace-scoped task sequence number */
  seq: number;
  /** Creator ID (auto-filled from token) */
  creatorId: string;
  /** Assignee ID (defaults to creator if omitted) */
  assigneeId: string;
  /** Task title */
  title: string;
  /** Task description */
  description: string;
  status: TaskResponseDtoStatus;
  priority: TaskResponseDtoPriority;
  /**
   * Additional info (plain text)
   * @nullable
   */
  info?: string | null;
  /** Creation timestamp */
  createdAt: string;
  /** Last update timestamp */
  updatedAt: string;
  creator?: TaskProfileDto;
  assignee?: TaskProfileDto;
  workspaceId: string;
}
