 
/**
 * Generated by orval v1.0 🍺
 * Do not edit manually.
 * Micro App API
 */

export type TaskResponseDtoStatus = typeof TaskResponseDtoStatus[keyof typeof TaskResponseDtoStatus];


 
export const TaskResponseDtoStatus = {
  backlog: 'backlog',
  ready_to_dev: 'ready_to_dev',
  in_dev: 'in_dev',
  blocker: 'blocker',
  in_testing: 'in_testing',
  in_review: 'in_review',
  done: 'done',
} as const;
