 
/**
 * Generated by orval v1.0 🍺
 * Do not edit manually.
 * Micro App API
 */

export interface TelegramAuthDto {
  /**
   * Telegram initData string from WebApp.initData
   * @maxLength 5000
   */
  initData: string;
}
