 
/**
 * Generated by orval v1.0 🍺
 * Do not edit manually.
 * Micro App API
 */
import type { UpdateProfileDtoContacts } from './updateProfileDtoContacts';

export interface UpdateProfileDto {
  /** @maxLength 255 */
  email?: string;
  /**
   * Username
   * @maxLength 255
   * @nullable
   */
  username?: string | null;
  /**
   * Full name
   * @maxLength 255
   * @nullable
   */
  fullName?: string | null;
  /** @nullable */
  lastActiveWorkspaceId?: string | null;
  /**
   * @maxLength 5000
   * @nullable
   */
  description?: string | null;
  /**
   * @maxLength 1000
   * @nullable
   */
  avatarUrl?: string | null;
  contacts?: UpdateProfileDtoContacts;
}
