 
/**
 * Generated by orval v1.0 🍺
 * Do not edit manually.
 * Micro App API
 */
import type { UpdateProfileDtoContacts } from './updateProfileDtoContacts';

export interface UpdateProfileDto {
  email?: string;
  /**
   * Username
   * @nullable
   */
  username?: string | null;
  /**
   * Full name
   * @nullable
   */
  fullName?: string | null;
  /** @nullable */
  role?: string | null;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  avatarUrl?: string | null;
  contacts?: UpdateProfileDtoContacts;
}
