 
/**
 * Generated by orval v1.0 🍺
 * Do not edit manually.
 * Micro App API
 */

export interface UpdateAccountReviewDto {
  /** Wallet address (public key) */
  authorAddress: string;
  /**
   * Rating from 1 to 5
   * @minimum 1
   * @maximum 5
   */
  rating?: number;
  /**
   * Optional review comment
   * @nullable
   */
  comment?: string | null;
}
