 
/**
 * Generated by orval v1.0 🍺
 * Do not edit manually.
 * Micro App API
 */
import type { UpdateTaskDtoStatus } from './updateTaskDtoStatus';
import type { UpdateTaskDtoPriority } from './updateTaskDtoPriority';

export interface UpdateTaskDto {
  /**
   * Task title
   * @maxLength 255
   */
  title?: string;
  /**
   * Task description
   * @maxLength 5000
   */
  description?: string;
  /** Task status */
  status?: UpdateTaskDtoStatus;
  /** Task priority */
  priority?: UpdateTaskDtoPriority;
  /** Assignee ID (defaults to creator if omitted) */
  assigneeId?: string;
  /**
   * Additional info (plain text)
   * @maxLength 5000
   */
  info?: string;
}
