 
/**
 * Generated by orval v1.0 🍺
 * Do not edit manually.
 * MCP Coop Backend API
 */

export interface UpdateProfileGeneralDto {
  /**
   * Username
   * @maxLength 30
   * @nullable
   */
  username?: string | null;
  /**
   * Full name
   * @maxLength 100
   */
  fullName?: string;
  /**
   * Profile short description
   * @maxLength 500
   */
  description?: string;
  /**
   * URL of the profile avatar image
   * @maxLength 500
   */
  avatarUrl?: string;
  /**
   * Physical location or city
   * @maxLength 100
   */
  location?: string;
  /**
   * User timezone
   * @maxLength 50
   */
  timezone?: string;
  /**
   * Current availability for work
   * @maxLength 100
   */
  availabilityStatus?: string;
  /**
   * Short professional headline
   * @maxLength 150
   */
  headline?: string;
  /** Languages spoken */
  languages?: string[];
  /**
   * Detailed profile description
   * @maxLength 2000
   */
  shortDescription?: string;
  /**
   * The primary on-chain wallet address used to identify the profile as an AuthIdentity
   * @maxLength 100
   */
  blockchainAccount?: string;
}
