 
/**
 * Generated by orval v1.0 🍺
 * Do not edit manually.
 * Micro App API
 */

export interface UpdateBlockchainAccountDto {
  /**
   * Optional self-description
   * @nullable
   */
  description?: string | null;
}
