 
/**
 * Generated by orval v1.0 🍺
 * Do not edit manually.
 * Micro App API
 */

export interface UpdateTaskCommentDto {
  /**
   * Comment text content
   * @maxLength 5000
   */
  content: string;
}
