 
/**
 * Generated by orval v1.0 🍺
 * Do not edit manually.
 * Micro App API
 */

/**
 * Member role
 */
export type UpdateWorkspaceMemberDtoRole = typeof UpdateWorkspaceMemberDtoRole[keyof typeof UpdateWorkspaceMemberDtoRole];


 
export const UpdateWorkspaceMemberDtoRole = {
  admin: 'admin',
  member: 'member',
} as const;
