 
/**
 * Generated by orval v1.0 🍺
 * Do not edit manually.
 * Micro App API
 */

/**
 * Task priority
 */
export type UpdateTaskDtoPriority = typeof UpdateTaskDtoPriority[keyof typeof UpdateTaskDtoPriority];


 
export const UpdateTaskDtoPriority = {
  low: 'low',
  medium: 'medium',
  high: 'high',
  critical: 'critical',
} as const;
