 
/**
 * Generated by orval v1.0 🍺
 * Do not edit manually.
 * Micro App API
 */

/**
 * Pricing tier
 */
export type UpdateWorkspaceDtoTier = typeof UpdateWorkspaceDtoTier[keyof typeof UpdateWorkspaceDtoTier];


 
export const UpdateWorkspaceDtoTier = {
  free: 'free',
  pro: 'pro',
} as const;
