 
/**
 * Generated by orval v1.0 🍺
 * Do not edit manually.
 * MCP Coop Backend API
 */

/**
 * Workspace type
 */
export type UpdateWorkspaceDtoType = typeof UpdateWorkspaceDtoType[keyof typeof UpdateWorkspaceDtoType];


 
export const UpdateWorkspaceDtoType = {
  private: 'private',
  group: 'group',
  channel: 'channel',
} as const;
