 
/**
 * Generated by orval v1.0 🍺
 * Do not edit manually.
 * Micro App API
 */
import type { UpdateTaskDtoStatus } from './updateTaskDtoStatus';
import type { UpdateTaskDtoPriority } from './updateTaskDtoPriority';

export interface UpdateTaskDto {
  /** Task title */
  title?: string;
  /** Task description */
  description?: string;
  /** Task status */
  status?: UpdateTaskDtoStatus;
  /** Task priority */
  priority?: UpdateTaskDtoPriority;
  /** Assignee ID (defaults to creator if omitted) */
  assigneeId?: string;
  /** Additional info (plain text) */
  info?: string;
}
