 
/**
 * Generated by orval v1.0 🍺
 * Do not edit manually.
 * Micro App API
 */
import type { UpdateWorkspaceDtoType } from './updateWorkspaceDtoType';
import type { UpdateWorkspaceDtoTier } from './updateWorkspaceDtoTier';
import type { WorkspaceSettingsDto } from './workspaceSettingsDto';

export interface UpdateWorkspaceDto {
  /** External ID (e.g. Telegram chat ID) */
  externalId?: string;
  /** Workspace name */
  name?: string;
  /** Workspace type */
  type?: UpdateWorkspaceDtoType;
  /** Pricing tier */
  tier?: UpdateWorkspaceDtoTier;
  settings?: WorkspaceSettingsDto;
}
