 
/**
 * Generated by orval v1.0 🍺
 * Do not edit manually.
 * Micro App API
 */
import type { ProfileSettingsDto } from './profileSettingsDto';

export interface UpdateProfileDto {
  email?: string;
  /**
   * Username
   * @nullable
   */
  username?: string | null;
  /** Full name */
  fullName?: string;
  settings?: ProfileSettingsDto;
}
