 
/**
 * Generated by orval v1.0 🍺
 * Do not edit manually.
 * MCP Coop Backend API
 */
import type { UpdateWorkspaceMemberDtoRole } from './updateWorkspaceMemberDtoRole';

export interface UpdateWorkspaceMemberDto {
  /** Workspace ID */
  workspaceId?: string;
  /** User profile ID */
  userId?: string;
  /** Member role */
  role?: UpdateWorkspaceMemberDtoRole;
}
