 
/**
 * Generated by orval v1.0 🍺
 * Do not edit manually.
 * Micro App API
 */

export interface UpdateTaskCriterionDto {
  /**
   * Criterion text
   * @maxLength 5000
   */
  text?: string;
  /** Completion status */
  isCompleted?: boolean;
  /**
   * Display order
   * @minimum 0
   */
  sortOrder?: number;
}
