 
/**
 * Generated by orval v1.0 🍺
 * Do not edit manually.
 * Micro App API
 */

/**
 * Task status
 */
export type UpdateTaskDtoStatus = typeof UpdateTaskDtoStatus[keyof typeof UpdateTaskDtoStatus];


 
export const UpdateTaskDtoStatus = {
  backlog: 'backlog',
  ready_to_dev: 'ready_to_dev',
  in_dev: 'in_dev',
  blocker: 'blocker',
  in_testing: 'in_testing',
  done: 'done',
} as const;
