 
/**
 * Generated by orval v1.0 🍺
 * Do not edit manually.
 * MCP Coop Backend API
 */

export interface UpsertSlideDto {
  /** Order of the slide */
  order: number;
  /**
   * Slide title
   * @maxLength 100
   */
  title: string;
  /**
   * Slide description or text content
   * @maxLength 500
   */
  description?: string;
  /**
   * URL of the slide media (image or video)
   * @maxLength 500
   */
  mediaUrl: string;
}
