 
/**
 * Generated by orval v1.0 🍺
 * Do not edit manually.
 * MCP Coop Backend API
 */
import type { SkillDto } from './skillDto';

export interface UpsertExperienceDto {
  /**
   * Company name for experience
   * @maxLength 100
   */
  companyName: string;
  /**
   * Role in the project
   * @maxLength 100
   */
  projectRole: string;
  /** Start date (ISO format) */
  startDate: string;
  /** End date (ISO format) */
  endDate?: string;
  /**
   * Description of the experience
   * @maxLength 2000
   */
  description?: string;
  /** Skills used in this experience */
  skills: SkillDto[];
}
