 
/**
 * Generated by orval v1.0 🍺
 * Do not edit manually.
 * Micro App API
 */

export interface VerifyEmailOtpDto {
  /** Email address */
  email: string;
  /**
   * 4-digit OTP code received via email
   * @minLength 4
   * @maxLength 4
   */
  code: string;
  /**
   * Username
   * @nullable
   */
  username?: string | null;
  /** Full name */
  fullName?: string;
}
