 
/**
 * Generated by orval v1.0 🍺
 * Do not edit manually.
 * Micro App API
 */

export interface VerifyEmailOtpDto {
  /** Email address */
  email: string;
  /**
   * 4-digit OTP code received via email
   * @minLength 6
   * @maxLength 6
   */
  code: string;
  /**
   * Username
   * @maxLength 255
   * @nullable
   */
  username?: string | null;
  /**
   * Full name
   * @maxLength 255
   */
  fullName?: string;
}
