 
/**
 * Generated by orval v1.0 🍺
 * Do not edit manually.
 * MCP Coop Backend API
 */

export interface WalletDto {
  /**
   * Blockchain network (e.g. solana, ethereum)
   * @maxLength 50
   */
  network: string;
  /**
   * Wallet address on the specified network
   * @maxLength 100
   */
  address: string;
  /** Indicates if this is the primary wallet for the network */
  isPrimary: boolean;
}
