 
/**
 * Generated by orval v1.0 🍺
 * Do not edit manually.
 * Micro App API
 */
import type { WorkspaceColumnsDto } from './workspaceColumnsDto';

export interface WorkspaceSettingsDto {
  columns: WorkspaceColumnsDto;
}
