 
/**
 * Generated by orval v1.0 🍺
 * Do not edit manually.
 * MCP Coop Backend API
 */
import type { WorkspaceColumnsDto } from './workspaceColumnsDto';

export interface WorkspaceSettingsDto {
  columns: WorkspaceColumnsDto;
}
