 
/**
 * Generated by orval v1.0 🍺
 * Do not edit manually.
 * Micro App API
 */
import type { ColumnStatusSettingsDto } from './columnStatusSettingsDto';

export interface WorkspaceColumnsDto {
  backlog: ColumnStatusSettingsDto;
  ready_to_dev: ColumnStatusSettingsDto;
  in_dev: ColumnStatusSettingsDto;
  in_testing: ColumnStatusSettingsDto;
  done: ColumnStatusSettingsDto;
  in_review?: ColumnStatusSettingsDto;
  blocker?: ColumnStatusSettingsDto;
}
