version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: mcp-coop-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - ~/.env
    volumes:
      - ./nginx.conf.template:/etc/nginx/templates/default.conf.template:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - client
    networks:
      - mcp-network

  client:
    image: ${IMAGE_URI}:latest
    container_name: ${PLATFORM_CONTAINER_NAME:-mcp-coop-platform}
    restart: always
    # Убран маппинг портов наружу, доступ только через nginx
    env_file:
      - ~/.env
    environment:
      - DATABASE_URL=postgresql://${MCP_COOP_PLARFORM}:${MCP_COOP_PLARFORM_PASSWORD}@postgres:5432/${MCP_COOP_PLARFORM_DB}?schema=public
    depends_on:
      setup-db:
        condition: service_completed_successfully
    networks:
      - mcp-network

  setup-db:
    image: ${IMAGE_URI}-builder:latest
    container_name: ${PLATFORM_CONTAINER_NAME:-mcp-coop-platform}-setup-db
    env_file:
      - ~/.env
    environment:
      - DATABASE_URL=postgresql://${MCP_COOP_PLARFORM}:${MCP_COOP_PLARFORM_PASSWORD}@postgres:5432/${MCP_COOP_PLARFORM_DB}?schema=public
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      sh -c "npx prisma db push --accept-data-loss && npx prisma db seed"
    networks:
      - mcp-network

  postgres:
    image: postgres:16
    container_name: ${PLATFORM_CONTAINER_NAME:-mcp-coop-platform}-db
    restart: always
    env_file:
      - ~/.env
    environment:
      POSTGRES_USER: ${MCP_COOP_PLARFORM}
      POSTGRES_PASSWORD: ${MCP_COOP_PLARFORM_PASSWORD}
      POSTGRES_DB: ${MCP_COOP_PLARFORM_DB}
    ports:
      - "${EXTERNAL_DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - mcp-network

volumes:
  postgres_data:


networks:
  mcp-network:
    name: mcp-network
