 
/**
 * Generated by orval v1.0 🍺
 * Do not edit manually.
 * Micro App API
 */
import type {
  MeResponseDto,
  ProfileFullResponseDto,
  ProfilesControllerFindAll200AllOf,
  ProfilesControllerFindAllParams,
  UpdateProfileDto
} from '.././models';

import { openApiMutator } from '../../interceptors/open-api.mutator';

/**
 * @summary Get your own profile
 */
export type myProfileControllerFindMeResponse200 = {
  data: MeResponseDto
  status: 200
}
    
export type myProfileControllerFindMeResponseSuccess = (myProfileControllerFindMeResponse200) & {
  headers: Headers;
};
;

export type myProfileControllerFindMeResponse = (myProfileControllerFindMeResponseSuccess)

export const getMyProfileControllerFindMeUrl = () => {


  

  return `/api/profiles/me`
}

export const myProfileControllerFindMe = async ( options?: RequestInit): Promise<myProfileControllerFindMeResponse> => {
  
  return openApiMutator<myProfileControllerFindMeResponse>(getMyProfileControllerFindMeUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Update your own profile
 */
export type myProfileControllerUpdateMeResponse200 = {
  data: MeResponseDto
  status: 200
}
    
export type myProfileControllerUpdateMeResponseSuccess = (myProfileControllerUpdateMeResponse200) & {
  headers: Headers;
};
;

export type myProfileControllerUpdateMeResponse = (myProfileControllerUpdateMeResponseSuccess)

export const getMyProfileControllerUpdateMeUrl = () => {


  

  return `/api/profiles/me`
}

export const myProfileControllerUpdateMe = async (updateProfileDto: UpdateProfileDto, options?: RequestInit): Promise<myProfileControllerUpdateMeResponse> => {
  
  return openApiMutator<myProfileControllerUpdateMeResponse>(getMyProfileControllerUpdateMeUrl(),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateProfileDto,)
  }
);}


/**
 * @summary Delete your own profile
 */
export type myProfileControllerRemoveMeResponse200 = {
  data: MeResponseDto
  status: 200
}
    
export type myProfileControllerRemoveMeResponseSuccess = (myProfileControllerRemoveMeResponse200) & {
  headers: Headers;
};
;

export type myProfileControllerRemoveMeResponse = (myProfileControllerRemoveMeResponseSuccess)

export const getMyProfileControllerRemoveMeUrl = () => {


  

  return `/api/profiles/me`
}

export const myProfileControllerRemoveMe = async ( options?: RequestInit): Promise<myProfileControllerRemoveMeResponse> => {
  
  return openApiMutator<myProfileControllerRemoveMeResponse>(getMyProfileControllerRemoveMeUrl(),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}


/**
 * @summary Get profiles from your workspaces
 */
export type profilesControllerFindAllResponse200 = {
  data: ProfilesControllerFindAll200AllOf
  status: 200
}
    
export type profilesControllerFindAllResponseSuccess = (profilesControllerFindAllResponse200) & {
  headers: Headers;
};
;

export type profilesControllerFindAllResponse = (profilesControllerFindAllResponseSuccess)

export const getProfilesControllerFindAllUrl = (params?: ProfilesControllerFindAllParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/profiles?${stringifiedParams}` : `/api/profiles`
}

export const profilesControllerFindAll = async (params?: ProfilesControllerFindAllParams, options?: RequestInit): Promise<profilesControllerFindAllResponse> => {
  
  return openApiMutator<profilesControllerFindAllResponse>(getProfilesControllerFindAllUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Get profile by ID (own or shared workspace)
 */
export type profilesControllerFindOneResponse200 = {
  data: ProfileFullResponseDto
  status: 200
}
    
export type profilesControllerFindOneResponseSuccess = (profilesControllerFindOneResponse200) & {
  headers: Headers;
};
;

export type profilesControllerFindOneResponse = (profilesControllerFindOneResponseSuccess)

export const getProfilesControllerFindOneUrl = (id: string,) => {


  

  return `/api/profiles/${id}`
}

export const profilesControllerFindOne = async (id: string, options?: RequestInit): Promise<profilesControllerFindOneResponse> => {
  
  return openApiMutator<profilesControllerFindOneResponse>(getProfilesControllerFindOneUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


