 
/**
 * Generated by orval v1.0 🍺
 * Do not edit manually.
 * Micro App API
 */
import type {
  ProfilesControllerFindAllParams,
  ProfilesControllerFindMe200,
  ProfilesControllerFindOne200,
  ProfilesControllerRemoveMe200,
  ProfilesControllerUpdateMe200,
  UpdateProfileDto
} from '.././models';

import { openApiMutator } from '../../interceptors/open-api.mutator';

/**
 * @summary Get profiles from your workspaces
 */
export type profilesControllerFindAllResponse200 = {
  data: void
  status: 200
}
    
export type profilesControllerFindAllResponseSuccess = (profilesControllerFindAllResponse200) & {
  headers: Headers;
};
;

export type profilesControllerFindAllResponse = (profilesControllerFindAllResponseSuccess)

export const getProfilesControllerFindAllUrl = (params?: ProfilesControllerFindAllParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/profiles?${stringifiedParams}` : `/api/profiles`
}

export const profilesControllerFindAll = async (params?: ProfilesControllerFindAllParams, options?: RequestInit): Promise<profilesControllerFindAllResponse> => {
  
  return openApiMutator<profilesControllerFindAllResponse>(getProfilesControllerFindAllUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Get your own profile
 */
export type profilesControllerFindMeResponse200 = {
  data: ProfilesControllerFindMe200
  status: 200
}
    
export type profilesControllerFindMeResponseSuccess = (profilesControllerFindMeResponse200) & {
  headers: Headers;
};
;

export type profilesControllerFindMeResponse = (profilesControllerFindMeResponseSuccess)

export const getProfilesControllerFindMeUrl = () => {


  

  return `/api/profiles/me`
}

export const profilesControllerFindMe = async ( options?: RequestInit): Promise<profilesControllerFindMeResponse> => {
  
  return openApiMutator<profilesControllerFindMeResponse>(getProfilesControllerFindMeUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Update your own profile
 */
export type profilesControllerUpdateMeResponse200 = {
  data: ProfilesControllerUpdateMe200
  status: 200
}
    
export type profilesControllerUpdateMeResponseSuccess = (profilesControllerUpdateMeResponse200) & {
  headers: Headers;
};
;

export type profilesControllerUpdateMeResponse = (profilesControllerUpdateMeResponseSuccess)

export const getProfilesControllerUpdateMeUrl = () => {


  

  return `/api/profiles/me`
}

export const profilesControllerUpdateMe = async (updateProfileDto: UpdateProfileDto, options?: RequestInit): Promise<profilesControllerUpdateMeResponse> => {
  
  return openApiMutator<profilesControllerUpdateMeResponse>(getProfilesControllerUpdateMeUrl(),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateProfileDto,)
  }
);}


/**
 * @summary Delete your own profile
 */
export type profilesControllerRemoveMeResponse200 = {
  data: ProfilesControllerRemoveMe200
  status: 200
}
    
export type profilesControllerRemoveMeResponseSuccess = (profilesControllerRemoveMeResponse200) & {
  headers: Headers;
};
;

export type profilesControllerRemoveMeResponse = (profilesControllerRemoveMeResponseSuccess)

export const getProfilesControllerRemoveMeUrl = () => {


  

  return `/api/profiles/me`
}

export const profilesControllerRemoveMe = async ( options?: RequestInit): Promise<profilesControllerRemoveMeResponse> => {
  
  return openApiMutator<profilesControllerRemoveMeResponse>(getProfilesControllerRemoveMeUrl(),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}


/**
 * @summary Get profile by ID (own or shared workspace)
 */
export type profilesControllerFindOneResponse200 = {
  data: ProfilesControllerFindOne200
  status: 200
}
    
export type profilesControllerFindOneResponseSuccess = (profilesControllerFindOneResponse200) & {
  headers: Headers;
};
;

export type profilesControllerFindOneResponse = (profilesControllerFindOneResponseSuccess)

export const getProfilesControllerFindOneUrl = (id: string,) => {


  

  return `/api/profiles/${id}`
}

export const profilesControllerFindOne = async (id: string, options?: RequestInit): Promise<profilesControllerFindOneResponse> => {
  
  return openApiMutator<profilesControllerFindOneResponse>(getProfilesControllerFindOneUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


