 
/**
 * Generated by orval v1.0 🍺
 * Do not edit manually.
 * MCP Coop Backend API
 */
import type {
  MeResponseDto,
  ProfileFullResponseDto,
  ProfilesControllerFindAll200AllOf,
  ProfilesControllerFindAllParams,
  SyncContactsDto,
  SyncSkillsDto,
  SyncWalletsDto,
  UpdateProfileGeneralDto,
  UpsertExperienceDto
} from '.././models';

import { openApiMutator } from '../../interceptors/open-api.mutator';

/**
 * @summary Get your own profile
 */
export type myProfileControllerFindMeResponse200 = {
  data: MeResponseDto
  status: 200
}
    
export type myProfileControllerFindMeResponseSuccess = (myProfileControllerFindMeResponse200) & {
  headers: Headers;
};
;

export type myProfileControllerFindMeResponse = (myProfileControllerFindMeResponseSuccess)

export const getMyProfileControllerFindMeUrl = () => {


  

  return `/api/profiles/me`
}

export const myProfileControllerFindMe = async ( options?: RequestInit): Promise<myProfileControllerFindMeResponse> => {
  
  return openApiMutator<myProfileControllerFindMeResponse>(getMyProfileControllerFindMeUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Delete your own profile
 */
export type myProfileControllerRemoveMeResponse200 = {
  data: MeResponseDto
  status: 200
}
    
export type myProfileControllerRemoveMeResponseSuccess = (myProfileControllerRemoveMeResponse200) & {
  headers: Headers;
};
;

export type myProfileControllerRemoveMeResponse = (myProfileControllerRemoveMeResponseSuccess)

export const getMyProfileControllerRemoveMeUrl = () => {


  

  return `/api/profiles/me`
}

export const myProfileControllerRemoveMe = async ( options?: RequestInit): Promise<myProfileControllerRemoveMeResponse> => {
  
  return openApiMutator<myProfileControllerRemoveMeResponse>(getMyProfileControllerRemoveMeUrl(),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}


/**
 * @summary Update general profile information
 */
export type myProfileControllerUpdateGeneralResponse200 = {
  data: MeResponseDto
  status: 200
}
    
export type myProfileControllerUpdateGeneralResponseSuccess = (myProfileControllerUpdateGeneralResponse200) & {
  headers: Headers;
};
;

export type myProfileControllerUpdateGeneralResponse = (myProfileControllerUpdateGeneralResponseSuccess)

export const getMyProfileControllerUpdateGeneralUrl = () => {


  

  return `/api/profiles/me/general`
}

export const myProfileControllerUpdateGeneral = async (updateProfileGeneralDto: UpdateProfileGeneralDto, options?: RequestInit): Promise<myProfileControllerUpdateGeneralResponse> => {
  
  return openApiMutator<myProfileControllerUpdateGeneralResponse>(getMyProfileControllerUpdateGeneralUrl(),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateProfileGeneralDto,)
  }
);}


/**
 * @summary Sync profile skills
 */
export type myProfileControllerSyncSkillsResponse200 = {
  data: void
  status: 200
}
    
export type myProfileControllerSyncSkillsResponseSuccess = (myProfileControllerSyncSkillsResponse200) & {
  headers: Headers;
};
;

export type myProfileControllerSyncSkillsResponse = (myProfileControllerSyncSkillsResponseSuccess)

export const getMyProfileControllerSyncSkillsUrl = () => {


  

  return `/api/profiles/me/skills`
}

export const myProfileControllerSyncSkills = async (syncSkillsDto: SyncSkillsDto, options?: RequestInit): Promise<myProfileControllerSyncSkillsResponse> => {
  
  return openApiMutator<myProfileControllerSyncSkillsResponse>(getMyProfileControllerSyncSkillsUrl(),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      syncSkillsDto,)
  }
);}


/**
 * @summary Sync profile contacts
 */
export type myProfileControllerSyncContactsResponse200 = {
  data: void
  status: 200
}
    
export type myProfileControllerSyncContactsResponseSuccess = (myProfileControllerSyncContactsResponse200) & {
  headers: Headers;
};
;

export type myProfileControllerSyncContactsResponse = (myProfileControllerSyncContactsResponseSuccess)

export const getMyProfileControllerSyncContactsUrl = () => {


  

  return `/api/profiles/me/contacts`
}

export const myProfileControllerSyncContacts = async (syncContactsDto: SyncContactsDto, options?: RequestInit): Promise<myProfileControllerSyncContactsResponse> => {
  
  return openApiMutator<myProfileControllerSyncContactsResponse>(getMyProfileControllerSyncContactsUrl(),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      syncContactsDto,)
  }
);}


/**
 * @summary Sync profile wallets
 */
export type myProfileControllerSyncWalletsResponse200 = {
  data: void
  status: 200
}
    
export type myProfileControllerSyncWalletsResponseSuccess = (myProfileControllerSyncWalletsResponse200) & {
  headers: Headers;
};
;

export type myProfileControllerSyncWalletsResponse = (myProfileControllerSyncWalletsResponseSuccess)

export const getMyProfileControllerSyncWalletsUrl = () => {


  

  return `/api/profiles/me/wallets`
}

export const myProfileControllerSyncWallets = async (syncWalletsDto: SyncWalletsDto, options?: RequestInit): Promise<myProfileControllerSyncWalletsResponse> => {
  
  return openApiMutator<myProfileControllerSyncWalletsResponse>(getMyProfileControllerSyncWalletsUrl(),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      syncWalletsDto,)
  }
);}


/**
 * @summary Create profile experience
 */
export type myProfileControllerCreateExperienceResponse201 = {
  data: void
  status: 201
}
    
export type myProfileControllerCreateExperienceResponseSuccess = (myProfileControllerCreateExperienceResponse201) & {
  headers: Headers;
};
;

export type myProfileControllerCreateExperienceResponse = (myProfileControllerCreateExperienceResponseSuccess)

export const getMyProfileControllerCreateExperienceUrl = () => {


  

  return `/api/profiles/me/experiences`
}

export const myProfileControllerCreateExperience = async (upsertExperienceDto: UpsertExperienceDto, options?: RequestInit): Promise<myProfileControllerCreateExperienceResponse> => {
  
  return openApiMutator<myProfileControllerCreateExperienceResponse>(getMyProfileControllerCreateExperienceUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      upsertExperienceDto,)
  }
);}


/**
 * @summary Update profile experience
 */
export type myProfileControllerUpdateExperienceResponse200 = {
  data: void
  status: 200
}
    
export type myProfileControllerUpdateExperienceResponseSuccess = (myProfileControllerUpdateExperienceResponse200) & {
  headers: Headers;
};
;

export type myProfileControllerUpdateExperienceResponse = (myProfileControllerUpdateExperienceResponseSuccess)

export const getMyProfileControllerUpdateExperienceUrl = (experienceId: string,) => {


  

  return `/api/profiles/me/experiences/${experienceId}`
}

export const myProfileControllerUpdateExperience = async (experienceId: string,
    upsertExperienceDto: UpsertExperienceDto, options?: RequestInit): Promise<myProfileControllerUpdateExperienceResponse> => {
  
  return openApiMutator<myProfileControllerUpdateExperienceResponse>(getMyProfileControllerUpdateExperienceUrl(experienceId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      upsertExperienceDto,)
  }
);}


/**
 * @summary Delete profile experience
 */
export type myProfileControllerDeleteExperienceResponse200 = {
  data: void
  status: 200
}
    
export type myProfileControllerDeleteExperienceResponseSuccess = (myProfileControllerDeleteExperienceResponse200) & {
  headers: Headers;
};
;

export type myProfileControllerDeleteExperienceResponse = (myProfileControllerDeleteExperienceResponseSuccess)

export const getMyProfileControllerDeleteExperienceUrl = (experienceId: string,) => {


  

  return `/api/profiles/me/experiences/${experienceId}`
}

export const myProfileControllerDeleteExperience = async (experienceId: string, options?: RequestInit): Promise<myProfileControllerDeleteExperienceResponse> => {
  
  return openApiMutator<myProfileControllerDeleteExperienceResponse>(getMyProfileControllerDeleteExperienceUrl(experienceId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}


/**
 * @summary Get profiles from your workspaces
 */
export type profilesControllerFindAllResponse200 = {
  data: ProfilesControllerFindAll200AllOf
  status: 200
}
    
export type profilesControllerFindAllResponseSuccess = (profilesControllerFindAllResponse200) & {
  headers: Headers;
};
;

export type profilesControllerFindAllResponse = (profilesControllerFindAllResponseSuccess)

export const getProfilesControllerFindAllUrl = (params?: ProfilesControllerFindAllParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/profiles?${stringifiedParams}` : `/api/profiles`
}

export const profilesControllerFindAll = async (params?: ProfilesControllerFindAllParams, options?: RequestInit): Promise<profilesControllerFindAllResponse> => {
  
  return openApiMutator<profilesControllerFindAllResponse>(getProfilesControllerFindAllUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Get profile by ID (own or shared workspace)
 */
export type profilesControllerFindOneResponse200 = {
  data: ProfileFullResponseDto
  status: 200
}
    
export type profilesControllerFindOneResponseSuccess = (profilesControllerFindOneResponse200) & {
  headers: Headers;
};
;

export type profilesControllerFindOneResponse = (profilesControllerFindOneResponseSuccess)

export const getProfilesControllerFindOneUrl = (id: string,) => {


  

  return `/api/profiles/${id}`
}

export const profilesControllerFindOne = async (id: string, options?: RequestInit): Promise<profilesControllerFindOneResponse> => {
  
  return openApiMutator<profilesControllerFindOneResponse>(getProfilesControllerFindOneUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


