 
/**
 * Generated by orval v1.0 🍺
 * Do not edit manually.
 * MCP Coop Backend API
 */
import type {
  CoopFullResponseDto,
  CoopResponseDto,
  CoopsControllerFindAll200AllOf,
  CoopsControllerFindAllParams,
  CreateCoopDto,
  PublishCoopDto,
  SyncCategoriesDto,
  SyncCoopContactsDto,
  SyncCoopWalletsDto,
  UpdateCoopGeneralDto,
  UpsertSlideDto
} from '.././models';

import { openApiMutator } from '../../interceptors/open-api.mutator';

/**
 * @summary List cooperatives (paginated, optional name search)
 */
export type coopsControllerFindAllResponse200 = {
  data: CoopsControllerFindAll200AllOf
  status: 200
}
    
export type coopsControllerFindAllResponseSuccess = (coopsControllerFindAllResponse200) & {
  headers: Headers;
};
;

export type coopsControllerFindAllResponse = (coopsControllerFindAllResponseSuccess)

export const getCoopsControllerFindAllUrl = (params?: CoopsControllerFindAllParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/coops?${stringifiedParams}` : `/api/coops`
}

export const coopsControllerFindAll = async (params?: CoopsControllerFindAllParams, options?: RequestInit): Promise<coopsControllerFindAllResponse> => {
  
  return openApiMutator<coopsControllerFindAllResponse>(getCoopsControllerFindAllUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Create a new off-chain cooperative
 */
export type coopsControllerCreateResponse200 = {
  data: CoopResponseDto
  status: 200
}
    
export type coopsControllerCreateResponseSuccess = (coopsControllerCreateResponse200) & {
  headers: Headers;
};
;

export type coopsControllerCreateResponse = (coopsControllerCreateResponseSuccess)

export const getCoopsControllerCreateUrl = () => {


  

  return `/api/coops`
}

export const coopsControllerCreate = async (createCoopDto: CreateCoopDto, options?: RequestInit): Promise<coopsControllerCreateResponse> => {
  
  return openApiMutator<coopsControllerCreateResponse>(getCoopsControllerCreateUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createCoopDto,)
  }
);}


/**
 * @summary Get cooperative by id (with members and management data)
 */
export type coopsControllerFindOneResponse200 = {
  data: CoopFullResponseDto
  status: 200
}
    
export type coopsControllerFindOneResponseSuccess = (coopsControllerFindOneResponse200) & {
  headers: Headers;
};
;

export type coopsControllerFindOneResponse = (coopsControllerFindOneResponseSuccess)

export const getCoopsControllerFindOneUrl = (id: string,) => {


  

  return `/api/coops/${id}`
}

export const coopsControllerFindOne = async (id: string, options?: RequestInit): Promise<coopsControllerFindOneResponse> => {
  
  return openApiMutator<coopsControllerFindOneResponse>(getCoopsControllerFindOneUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Publish off-chain cooperative to blockchain
 */
export type coopsControllerPublishResponse200 = {
  data: void
  status: 200
}
    
export type coopsControllerPublishResponseSuccess = (coopsControllerPublishResponse200) & {
  headers: Headers;
};
;

export type coopsControllerPublishResponse = (coopsControllerPublishResponseSuccess)

export const getCoopsControllerPublishUrl = (id: string,) => {


  

  return `/api/coops/${id}/publish`
}

export const coopsControllerPublish = async (id: string,
    publishCoopDto: PublishCoopDto, options?: RequestInit): Promise<coopsControllerPublishResponse> => {
  
  return openApiMutator<coopsControllerPublishResponse>(getCoopsControllerPublishUrl(id),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      publishCoopDto,)
  }
);}


/**
 * @summary Update general coop information
 */
export type coopsControllerUpdateGeneralResponse200 = {
  data: CoopResponseDto
  status: 200
}
    
export type coopsControllerUpdateGeneralResponseSuccess = (coopsControllerUpdateGeneralResponse200) & {
  headers: Headers;
};
;

export type coopsControllerUpdateGeneralResponse = (coopsControllerUpdateGeneralResponseSuccess)

export const getCoopsControllerUpdateGeneralUrl = (id: string,) => {


  

  return `/api/coops/${id}/general`
}

export const coopsControllerUpdateGeneral = async (id: string,
    updateCoopGeneralDto: UpdateCoopGeneralDto, options?: RequestInit): Promise<coopsControllerUpdateGeneralResponse> => {
  
  return openApiMutator<coopsControllerUpdateGeneralResponse>(getCoopsControllerUpdateGeneralUrl(id),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      updateCoopGeneralDto,)
  }
);}


/**
 * @summary Sync cooperative categories
 */
export type coopsControllerSyncCategoriesResponse200 = {
  data: void
  status: 200
}
    
export type coopsControllerSyncCategoriesResponseSuccess = (coopsControllerSyncCategoriesResponse200) & {
  headers: Headers;
};
;

export type coopsControllerSyncCategoriesResponse = (coopsControllerSyncCategoriesResponseSuccess)

export const getCoopsControllerSyncCategoriesUrl = (id: string,) => {


  

  return `/api/coops/${id}/categories`
}

export const coopsControllerSyncCategories = async (id: string,
    syncCategoriesDto: SyncCategoriesDto, options?: RequestInit): Promise<coopsControllerSyncCategoriesResponse> => {
  
  return openApiMutator<coopsControllerSyncCategoriesResponse>(getCoopsControllerSyncCategoriesUrl(id),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      syncCategoriesDto,)
  }
);}


/**
 * @summary Sync cooperative contacts
 */
export type coopsControllerSyncContactsResponse200 = {
  data: void
  status: 200
}
    
export type coopsControllerSyncContactsResponseSuccess = (coopsControllerSyncContactsResponse200) & {
  headers: Headers;
};
;

export type coopsControllerSyncContactsResponse = (coopsControllerSyncContactsResponseSuccess)

export const getCoopsControllerSyncContactsUrl = (id: string,) => {


  

  return `/api/coops/${id}/contacts`
}

export const coopsControllerSyncContacts = async (id: string,
    syncCoopContactsDto: SyncCoopContactsDto, options?: RequestInit): Promise<coopsControllerSyncContactsResponse> => {
  
  return openApiMutator<coopsControllerSyncContactsResponse>(getCoopsControllerSyncContactsUrl(id),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      syncCoopContactsDto,)
  }
);}


/**
 * @summary Sync cooperative wallets
 */
export type coopsControllerSyncWalletsResponse200 = {
  data: void
  status: 200
}
    
export type coopsControllerSyncWalletsResponseSuccess = (coopsControllerSyncWalletsResponse200) & {
  headers: Headers;
};
;

export type coopsControllerSyncWalletsResponse = (coopsControllerSyncWalletsResponseSuccess)

export const getCoopsControllerSyncWalletsUrl = (id: string,) => {


  

  return `/api/coops/${id}/wallets`
}

export const coopsControllerSyncWallets = async (id: string,
    syncCoopWalletsDto: SyncCoopWalletsDto, options?: RequestInit): Promise<coopsControllerSyncWalletsResponse> => {
  
  return openApiMutator<coopsControllerSyncWalletsResponse>(getCoopsControllerSyncWalletsUrl(id),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      syncCoopWalletsDto,)
  }
);}


/**
 * @summary Create cooperative presentation slide
 */
export type coopsControllerCreateSlideResponse201 = {
  data: void
  status: 201
}
    
export type coopsControllerCreateSlideResponseSuccess = (coopsControllerCreateSlideResponse201) & {
  headers: Headers;
};
;

export type coopsControllerCreateSlideResponse = (coopsControllerCreateSlideResponseSuccess)

export const getCoopsControllerCreateSlideUrl = (id: string,) => {


  

  return `/api/coops/${id}/slides`
}

export const coopsControllerCreateSlide = async (id: string,
    upsertSlideDto: UpsertSlideDto, options?: RequestInit): Promise<coopsControllerCreateSlideResponse> => {
  
  return openApiMutator<coopsControllerCreateSlideResponse>(getCoopsControllerCreateSlideUrl(id),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      upsertSlideDto,)
  }
);}


/**
 * @summary Update cooperative presentation slide
 */
export type coopsControllerUpdateSlideResponse200 = {
  data: void
  status: 200
}
    
export type coopsControllerUpdateSlideResponseSuccess = (coopsControllerUpdateSlideResponse200) & {
  headers: Headers;
};
;

export type coopsControllerUpdateSlideResponse = (coopsControllerUpdateSlideResponseSuccess)

export const getCoopsControllerUpdateSlideUrl = (id: string,
    slideId: string,) => {


  

  return `/api/coops/${id}/slides/${slideId}`
}

export const coopsControllerUpdateSlide = async (id: string,
    slideId: string,
    upsertSlideDto: UpsertSlideDto, options?: RequestInit): Promise<coopsControllerUpdateSlideResponse> => {
  
  return openApiMutator<coopsControllerUpdateSlideResponse>(getCoopsControllerUpdateSlideUrl(id,slideId),
  {      
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      upsertSlideDto,)
  }
);}


/**
 * @summary Delete cooperative presentation slide
 */
export type coopsControllerDeleteSlideResponse200 = {
  data: void
  status: 200
}
    
export type coopsControllerDeleteSlideResponseSuccess = (coopsControllerDeleteSlideResponse200) & {
  headers: Headers;
};
;

export type coopsControllerDeleteSlideResponse = (coopsControllerDeleteSlideResponseSuccess)

export const getCoopsControllerDeleteSlideUrl = (id: string,
    slideId: string,) => {


  

  return `/api/coops/${id}/slides/${slideId}`
}

export const coopsControllerDeleteSlide = async (id: string,
    slideId: string, options?: RequestInit): Promise<coopsControllerDeleteSlideResponse> => {
  
  return openApiMutator<coopsControllerDeleteSlideResponse>(getCoopsControllerDeleteSlideUrl(id,slideId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}


