 
/**
 * Generated by orval v1.0 🍺
 * Do not edit manually.
 * Micro App API
 */
import type {
  CoopFullResponseDto,
  CoopsControllerFindAll200AllOf,
  CoopsControllerFindAllParams
} from '.././models';

import { openApiMutator } from '../../interceptors/open-api.mutator';

/**
 * @summary List cooperatives (paginated, optional name search)
 */
export type coopsControllerFindAllResponse200 = {
  data: CoopsControllerFindAll200AllOf
  status: 200
}
    
export type coopsControllerFindAllResponseSuccess = (coopsControllerFindAllResponse200) & {
  headers: Headers;
};
;

export type coopsControllerFindAllResponse = (coopsControllerFindAllResponseSuccess)

export const getCoopsControllerFindAllUrl = (params?: CoopsControllerFindAllParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/coops?${stringifiedParams}` : `/api/coops`
}

export const coopsControllerFindAll = async (params?: CoopsControllerFindAllParams, options?: RequestInit): Promise<coopsControllerFindAllResponse> => {
  
  return openApiMutator<coopsControllerFindAllResponse>(getCoopsControllerFindAllUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Get cooperative by id (with members and management data)
 */
export type coopsControllerFindOneResponse200 = {
  data: CoopFullResponseDto
  status: 200
}
    
export type coopsControllerFindOneResponseSuccess = (coopsControllerFindOneResponse200) & {
  headers: Headers;
};
;

export type coopsControllerFindOneResponse = (coopsControllerFindOneResponseSuccess)

export const getCoopsControllerFindOneUrl = (id: string,) => {


  

  return `/api/coops/${id}`
}

export const coopsControllerFindOne = async (id: string, options?: RequestInit): Promise<coopsControllerFindOneResponse> => {
  
  return openApiMutator<coopsControllerFindOneResponse>(getCoopsControllerFindOneUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


