 
/**
 * Generated by orval v1.0 🍺
 * Do not edit manually.
 * Micro App API
 */
import type {
  AuthSuccessResponse,
  LinkTelegramDto,
  RequestEmailOtpDto,
  RequestEmailOtpResponseDto,
  TelegramLoginDto,
  VerifyEmailOtpDto
} from '.././models';

import { openApiMutator } from '../../interceptors/open-api.mutator';

/**
 * @summary Authenticate via Telegram initData
 */
export type authControllerLoginTelegramResponse200 = {
  data: AuthSuccessResponse
  status: 200
}

export type authControllerLoginTelegramResponse400 = {
  data: void
  status: 400
}

export type authControllerLoginTelegramResponse401 = {
  data: void
  status: 401
}
    
export type authControllerLoginTelegramResponseSuccess = (authControllerLoginTelegramResponse200) & {
  headers: Headers;
};
export type authControllerLoginTelegramResponseError = (authControllerLoginTelegramResponse400 | authControllerLoginTelegramResponse401) & {
  headers: Headers;
};

export type authControllerLoginTelegramResponse = (authControllerLoginTelegramResponseSuccess | authControllerLoginTelegramResponseError)

export const getAuthControllerLoginTelegramUrl = () => {


  

  return `/api/auth/telegram`
}

export const authControllerLoginTelegram = async (telegramLoginDto: TelegramLoginDto, options?: RequestInit): Promise<authControllerLoginTelegramResponse> => {
  
  return openApiMutator<authControllerLoginTelegramResponse>(getAuthControllerLoginTelegramUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      telegramLoginDto,)
  }
);}


/**
 * @summary Request an OTP code for passwordless login/registration
 */
export type authControllerRequestEmailOtpResponse200 = {
  data: RequestEmailOtpResponseDto
  status: 200
}

export type authControllerRequestEmailOtpResponse400 = {
  data: void
  status: 400
}
    
export type authControllerRequestEmailOtpResponseSuccess = (authControllerRequestEmailOtpResponse200) & {
  headers: Headers;
};
export type authControllerRequestEmailOtpResponseError = (authControllerRequestEmailOtpResponse400) & {
  headers: Headers;
};

export type authControllerRequestEmailOtpResponse = (authControllerRequestEmailOtpResponseSuccess | authControllerRequestEmailOtpResponseError)

export const getAuthControllerRequestEmailOtpUrl = () => {


  

  return `/api/auth/email/request`
}

export const authControllerRequestEmailOtp = async (requestEmailOtpDto: RequestEmailOtpDto, options?: RequestInit): Promise<authControllerRequestEmailOtpResponse> => {
  
  return openApiMutator<authControllerRequestEmailOtpResponse>(getAuthControllerRequestEmailOtpUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      requestEmailOtpDto,)
  }
);}


/**
 * @summary Verify OTP code and authenticate user
 */
export type authControllerVerifyEmailOtpResponse200 = {
  data: AuthSuccessResponse
  status: 200
}

export type authControllerVerifyEmailOtpResponse400 = {
  data: void
  status: 400
}

export type authControllerVerifyEmailOtpResponse401 = {
  data: void
  status: 401
}
    
export type authControllerVerifyEmailOtpResponseSuccess = (authControllerVerifyEmailOtpResponse200) & {
  headers: Headers;
};
export type authControllerVerifyEmailOtpResponseError = (authControllerVerifyEmailOtpResponse400 | authControllerVerifyEmailOtpResponse401) & {
  headers: Headers;
};

export type authControllerVerifyEmailOtpResponse = (authControllerVerifyEmailOtpResponseSuccess | authControllerVerifyEmailOtpResponseError)

export const getAuthControllerVerifyEmailOtpUrl = () => {


  

  return `/api/auth/email/verify`
}

export const authControllerVerifyEmailOtp = async (verifyEmailOtpDto: VerifyEmailOtpDto, options?: RequestInit): Promise<authControllerVerifyEmailOtpResponse> => {
  
  return openApiMutator<authControllerVerifyEmailOtpResponse>(getAuthControllerVerifyEmailOtpUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      verifyEmailOtpDto,)
  }
);}


/**
 * @summary Link Telegram account to current web account
 */
export type authControllerLinkTelegramAccountResponse200 = {
  data: AuthSuccessResponse
  status: 200
}

export type authControllerLinkTelegramAccountResponse400 = {
  data: void
  status: 400
}

export type authControllerLinkTelegramAccountResponse401 = {
  data: void
  status: 401
}
    
export type authControllerLinkTelegramAccountResponseSuccess = (authControllerLinkTelegramAccountResponse200) & {
  headers: Headers;
};
export type authControllerLinkTelegramAccountResponseError = (authControllerLinkTelegramAccountResponse400 | authControllerLinkTelegramAccountResponse401) & {
  headers: Headers;
};

export type authControllerLinkTelegramAccountResponse = (authControllerLinkTelegramAccountResponseSuccess | authControllerLinkTelegramAccountResponseError)

export const getAuthControllerLinkTelegramAccountUrl = () => {


  

  return `/api/auth/link-telegram`
}

export const authControllerLinkTelegramAccount = async (linkTelegramDto: LinkTelegramDto, options?: RequestInit): Promise<authControllerLinkTelegramAccountResponse> => {
  
  return openApiMutator<authControllerLinkTelegramAccountResponse>(getAuthControllerLinkTelegramAccountUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      linkTelegramDto,)
  }
);}


/**
 * @summary Logout and clear refresh token
 */
export type authControllerLogoutResponse200 = {
  data: AuthSuccessResponse
  status: 200
}

export type authControllerLogoutResponse401 = {
  data: void
  status: 401
}
    
export type authControllerLogoutResponseSuccess = (authControllerLogoutResponse200) & {
  headers: Headers;
};
export type authControllerLogoutResponseError = (authControllerLogoutResponse401) & {
  headers: Headers;
};

export type authControllerLogoutResponse = (authControllerLogoutResponseSuccess | authControllerLogoutResponseError)

export const getAuthControllerLogoutUrl = () => {


  

  return `/api/auth/logout`
}

export const authControllerLogout = async ( options?: RequestInit): Promise<authControllerLogoutResponse> => {
  
  return openApiMutator<authControllerLogoutResponse>(getAuthControllerLogoutUrl(),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}


/**
 * @summary Refresh access token using refresh token
 */
export type authControllerRefreshResponse200 = {
  data: AuthSuccessResponse
  status: 200
}

export type authControllerRefreshResponse401 = {
  data: void
  status: 401
}
    
export type authControllerRefreshResponseSuccess = (authControllerRefreshResponse200) & {
  headers: Headers;
};
export type authControllerRefreshResponseError = (authControllerRefreshResponse401) & {
  headers: Headers;
};

export type authControllerRefreshResponse = (authControllerRefreshResponseSuccess | authControllerRefreshResponseError)

export const getAuthControllerRefreshUrl = () => {


  

  return `/api/auth/refresh`
}

export const authControllerRefresh = async ( options?: RequestInit): Promise<authControllerRefreshResponse> => {
  
  return openApiMutator<authControllerRefreshResponse>(getAuthControllerRefreshUrl(),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}


