 
/**
 * Generated by orval v1.0 🍺
 * Do not edit manually.
 * Micro App API
 */
import type {
  AuthControllerOauthCallbackParams,
  AuthSuccessResponse,
  LinkTelegramDto,
  LoginDto,
  RegisterDto,
  TelegramLoginDto
} from '.././models';

import { openApiMutator } from '../../interceptors/open-api.mutator';

/**
 * @summary Authenticate via Telegram initData
 */
export type authControllerLoginTelegramResponse200 = {
  data: AuthSuccessResponse
  status: 200
}
    
export type authControllerLoginTelegramResponseSuccess = (authControllerLoginTelegramResponse200) & {
  headers: Headers;
};
;

export type authControllerLoginTelegramResponse = (authControllerLoginTelegramResponseSuccess)

export const getAuthControllerLoginTelegramUrl = () => {


  

  return `/api/auth/telegram`
}

export const authControllerLoginTelegram = async (telegramLoginDto: TelegramLoginDto, options?: RequestInit): Promise<authControllerLoginTelegramResponse> => {
  
  return openApiMutator<authControllerLoginTelegramResponse>(getAuthControllerLoginTelegramUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      telegramLoginDto,)
  }
);}


/**
 * @summary Register a new web account
 */
export type authControllerRegisterResponse201 = {
  data: AuthSuccessResponse
  status: 201
}
    
export type authControllerRegisterResponseSuccess = (authControllerRegisterResponse201) & {
  headers: Headers;
};
;

export type authControllerRegisterResponse = (authControllerRegisterResponseSuccess)

export const getAuthControllerRegisterUrl = () => {


  

  return `/api/auth/register`
}

export const authControllerRegister = async (registerDto: RegisterDto, options?: RequestInit): Promise<authControllerRegisterResponse> => {
  
  return openApiMutator<authControllerRegisterResponse>(getAuthControllerRegisterUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      registerDto,)
  }
);}


/**
 * @summary Login with email and password
 */
export type authControllerLoginResponse200 = {
  data: AuthSuccessResponse
  status: 200
}
    
export type authControllerLoginResponseSuccess = (authControllerLoginResponse200) & {
  headers: Headers;
};
;

export type authControllerLoginResponse = (authControllerLoginResponseSuccess)

export const getAuthControllerLoginUrl = () => {


  

  return `/api/auth/login`
}

export const authControllerLogin = async (loginDto: LoginDto, options?: RequestInit): Promise<authControllerLoginResponse> => {
  
  return openApiMutator<authControllerLoginResponse>(getAuthControllerLoginUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      loginDto,)
  }
);}


/**
 * @summary Redirect to OAuth provider authorization page
 */
export type authControllerOauthRedirectResponse200 = {
  data: void
  status: 200
}
    
export type authControllerOauthRedirectResponseSuccess = (authControllerOauthRedirectResponse200) & {
  headers: Headers;
};
;

export type authControllerOauthRedirectResponse = (authControllerOauthRedirectResponseSuccess)

export const getAuthControllerOauthRedirectUrl = (provider: string,) => {


  

  return `/api/auth/oauth/${provider}`
}

export const authControllerOauthRedirect = async (provider: string, options?: RequestInit): Promise<authControllerOauthRedirectResponse> => {
  
  return openApiMutator<authControllerOauthRedirectResponse>(getAuthControllerOauthRedirectUrl(provider),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary OAuth provider callback — exchanges code for tokens
 */
export type authControllerOauthCallbackResponse200 = {
  data: void
  status: 200
}
    
export type authControllerOauthCallbackResponseSuccess = (authControllerOauthCallbackResponse200) & {
  headers: Headers;
};
;

export type authControllerOauthCallbackResponse = (authControllerOauthCallbackResponseSuccess)

export const getAuthControllerOauthCallbackUrl = (provider: string,
    params: AuthControllerOauthCallbackParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/auth/oauth/${provider}/callback?${stringifiedParams}` : `/api/auth/oauth/${provider}/callback`
}

export const authControllerOauthCallback = async (provider: string,
    params: AuthControllerOauthCallbackParams, options?: RequestInit): Promise<authControllerOauthCallbackResponse> => {
  
  return openApiMutator<authControllerOauthCallbackResponse>(getAuthControllerOauthCallbackUrl(provider,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Link Telegram account to current web account
 */
export type authControllerLinkTelegramAccountResponse200 = {
  data: AuthSuccessResponse
  status: 200
}
    
export type authControllerLinkTelegramAccountResponseSuccess = (authControllerLinkTelegramAccountResponse200) & {
  headers: Headers;
};
;

export type authControllerLinkTelegramAccountResponse = (authControllerLinkTelegramAccountResponseSuccess)

export const getAuthControllerLinkTelegramAccountUrl = () => {


  

  return `/api/auth/link-telegram`
}

export const authControllerLinkTelegramAccount = async (linkTelegramDto: LinkTelegramDto, options?: RequestInit): Promise<authControllerLinkTelegramAccountResponse> => {
  
  return openApiMutator<authControllerLinkTelegramAccountResponse>(getAuthControllerLinkTelegramAccountUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      linkTelegramDto,)
  }
);}


/**
 * @summary Logout and clear refresh token
 */
export type authControllerLogoutResponse200 = {
  data: AuthSuccessResponse
  status: 200
}
    
export type authControllerLogoutResponseSuccess = (authControllerLogoutResponse200) & {
  headers: Headers;
};
;

export type authControllerLogoutResponse = (authControllerLogoutResponseSuccess)

export const getAuthControllerLogoutUrl = () => {


  

  return `/api/auth/logout`
}

export const authControllerLogout = async ( options?: RequestInit): Promise<authControllerLogoutResponse> => {
  
  return openApiMutator<authControllerLogoutResponse>(getAuthControllerLogoutUrl(),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}


/**
 * @summary Refresh access token using refresh token
 */
export type authControllerRefreshResponse200 = {
  data: AuthSuccessResponse
  status: 200
}
    
export type authControllerRefreshResponseSuccess = (authControllerRefreshResponse200) & {
  headers: Headers;
};
;

export type authControllerRefreshResponse = (authControllerRefreshResponseSuccess)

export const getAuthControllerRefreshUrl = () => {


  

  return `/api/auth/refresh`
}

export const authControllerRefresh = async ( options?: RequestInit): Promise<authControllerRefreshResponse> => {
  
  return openApiMutator<authControllerRefreshResponse>(getAuthControllerRefreshUrl(),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}


