 
/**
 * Generated by orval v1.0 🍺
 * Do not edit manually.
 * Micro App API
 */
import type {
  AuthSuccessResponse,
  OAuthControllerCallbackParams,
  RequestEmailOtpDto,
  RequestEmailOtpResponseDto,
  TelegramAuthDto,
  VerifyEmailOtpDto
} from '.././models';

import { openApiMutator } from '../../interceptors/open-api.mutator';

/**
 * @summary Request an OTP code for passwordless login/registration
 */
export type emailOtpControllerRequestOtpResponse200 = {
  data: RequestEmailOtpResponseDto
  status: 200
}

export type emailOtpControllerRequestOtpResponse400 = {
  data: void
  status: 400
}
    
export type emailOtpControllerRequestOtpResponseSuccess = (emailOtpControllerRequestOtpResponse200) & {
  headers: Headers;
};
export type emailOtpControllerRequestOtpResponseError = (emailOtpControllerRequestOtpResponse400) & {
  headers: Headers;
};

export type emailOtpControllerRequestOtpResponse = (emailOtpControllerRequestOtpResponseSuccess | emailOtpControllerRequestOtpResponseError)

export const getEmailOtpControllerRequestOtpUrl = () => {


  

  return `/api/auth/email/request`
}

export const emailOtpControllerRequestOtp = async (requestEmailOtpDto: RequestEmailOtpDto, options?: RequestInit): Promise<emailOtpControllerRequestOtpResponse> => {
  
  return openApiMutator<emailOtpControllerRequestOtpResponse>(getEmailOtpControllerRequestOtpUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      requestEmailOtpDto,)
  }
);}


/**
 * @summary Verify OTP code and authenticate user
 */
export type emailOtpControllerVerifyOtpResponse200 = {
  data: AuthSuccessResponse
  status: 200
}

export type emailOtpControllerVerifyOtpResponse400 = {
  data: void
  status: 400
}

export type emailOtpControllerVerifyOtpResponse401 = {
  data: void
  status: 401
}
    
export type emailOtpControllerVerifyOtpResponseSuccess = (emailOtpControllerVerifyOtpResponse200) & {
  headers: Headers;
};
export type emailOtpControllerVerifyOtpResponseError = (emailOtpControllerVerifyOtpResponse400 | emailOtpControllerVerifyOtpResponse401) & {
  headers: Headers;
};

export type emailOtpControllerVerifyOtpResponse = (emailOtpControllerVerifyOtpResponseSuccess | emailOtpControllerVerifyOtpResponseError)

export const getEmailOtpControllerVerifyOtpUrl = () => {


  

  return `/api/auth/email/verify`
}

export const emailOtpControllerVerifyOtp = async (verifyEmailOtpDto: VerifyEmailOtpDto, options?: RequestInit): Promise<emailOtpControllerVerifyOtpResponse> => {
  
  return openApiMutator<emailOtpControllerVerifyOtpResponse>(getEmailOtpControllerVerifyOtpUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      verifyEmailOtpDto,)
  }
);}


/**
 * @summary Redirect to OAuth provider authorization page
 */
export type oAuthControllerRedirectResponse200 = {
  data: void
  status: 200
}
    
export type oAuthControllerRedirectResponseSuccess = (oAuthControllerRedirectResponse200) & {
  headers: Headers;
};
;

export type oAuthControllerRedirectResponse = (oAuthControllerRedirectResponseSuccess)

export const getOAuthControllerRedirectUrl = (provider: string,) => {


  

  return `/api/auth/oauth/${provider}`
}

export const oAuthControllerRedirect = async (provider: string, options?: RequestInit): Promise<oAuthControllerRedirectResponse> => {
  
  return openApiMutator<oAuthControllerRedirectResponse>(getOAuthControllerRedirectUrl(provider),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary OAuth provider callback — exchanges code for tokens
 */
export type oAuthControllerCallbackResponse200 = {
  data: void
  status: 200
}
    
export type oAuthControllerCallbackResponseSuccess = (oAuthControllerCallbackResponse200) & {
  headers: Headers;
};
;

export type oAuthControllerCallbackResponse = (oAuthControllerCallbackResponseSuccess)

export const getOAuthControllerCallbackUrl = (provider: string,
    params: OAuthControllerCallbackParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/auth/oauth/${provider}/callback?${stringifiedParams}` : `/api/auth/oauth/${provider}/callback`
}

export const oAuthControllerCallback = async (provider: string,
    params: OAuthControllerCallbackParams, options?: RequestInit): Promise<oAuthControllerCallbackResponse> => {
  
  return openApiMutator<oAuthControllerCallbackResponse>(getOAuthControllerCallbackUrl(provider,params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}


/**
 * @summary Authenticate or link Telegram account. Links to current profile if JWT is present, otherwise creates or logs into an account.
 */
export type sessionControllerTelegramResponse200 = {
  data: AuthSuccessResponse
  status: 200
}

export type sessionControllerTelegramResponse400 = {
  data: void
  status: 400
}

export type sessionControllerTelegramResponse401 = {
  data: void
  status: 401
}
    
export type sessionControllerTelegramResponseSuccess = (sessionControllerTelegramResponse200) & {
  headers: Headers;
};
export type sessionControllerTelegramResponseError = (sessionControllerTelegramResponse400 | sessionControllerTelegramResponse401) & {
  headers: Headers;
};

export type sessionControllerTelegramResponse = (sessionControllerTelegramResponseSuccess | sessionControllerTelegramResponseError)

export const getSessionControllerTelegramUrl = () => {


  

  return `/api/auth/telegram`
}

export const sessionControllerTelegram = async (telegramAuthDto: TelegramAuthDto, options?: RequestInit): Promise<sessionControllerTelegramResponse> => {
  
  return openApiMutator<sessionControllerTelegramResponse>(getSessionControllerTelegramUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      telegramAuthDto,)
  }
);}


/**
 * @summary Logout and clear refresh token
 */
export type sessionControllerLogoutResponse200 = {
  data: AuthSuccessResponse
  status: 200
}

export type sessionControllerLogoutResponse401 = {
  data: void
  status: 401
}
    
export type sessionControllerLogoutResponseSuccess = (sessionControllerLogoutResponse200) & {
  headers: Headers;
};
export type sessionControllerLogoutResponseError = (sessionControllerLogoutResponse401) & {
  headers: Headers;
};

export type sessionControllerLogoutResponse = (sessionControllerLogoutResponseSuccess | sessionControllerLogoutResponseError)

export const getSessionControllerLogoutUrl = () => {


  

  return `/api/auth/logout`
}

export const sessionControllerLogout = async ( options?: RequestInit): Promise<sessionControllerLogoutResponse> => {
  
  return openApiMutator<sessionControllerLogoutResponse>(getSessionControllerLogoutUrl(),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}


/**
 * @summary Refresh access token using refresh token
 */
export type sessionControllerRefreshResponse200 = {
  data: AuthSuccessResponse
  status: 200
}

export type sessionControllerRefreshResponse401 = {
  data: void
  status: 401
}
    
export type sessionControllerRefreshResponseSuccess = (sessionControllerRefreshResponse200) & {
  headers: Headers;
};
export type sessionControllerRefreshResponseError = (sessionControllerRefreshResponse401) & {
  headers: Headers;
};

export type sessionControllerRefreshResponse = (sessionControllerRefreshResponseSuccess | sessionControllerRefreshResponseError)

export const getSessionControllerRefreshUrl = () => {


  

  return `/api/auth/refresh`
}

export const sessionControllerRefresh = async ( options?: RequestInit): Promise<sessionControllerRefreshResponse> => {
  
  return openApiMutator<sessionControllerRefreshResponse>(getSessionControllerRefreshUrl(),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}


